version: "3"

services: 

  mongo:

    image: mongo

    container_name: mongo

 #   restart: always

    volumes:

      - ./mongod.conf:/etc/mongod.conf

     # - ./logs:/var/log/mongod/

     # - ./db:/var/lib/mongodb

      #- ./mongod.service:/lib/systemd/system/mongod.service

    ports:

      - "27017:27017"

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/posts --quiet
      interval: 5s
      timeout: 5s
      retries: 8

  app:
    depends_on:
      mongo:
        condition: service_healthy

    container_name: small_app_update

    restart: always

    image: fredericoco121/app_posts

    ports:

      - "80:3000"

    links:

      - mongo

    environment: 

      - DB_HOST=mongodb://mongo:27017/posts